add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_654bd15cadc6f',
	'title' => 'Jurisdiction Details',
	'fields' => array(
		array(
			'key' => 'field_654bd15d0bae5',
			'label' => 'Agency Name',
			'name' => 'agency_name',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_654bd1a86b080',
			'label' => 'Main Address',
			'name' => 'address_jurisdiction',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_654bd1c07a748',
			'label' => 'Phone',
			'name' => 'phone_jurisdiction',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_660095ec0b7e6',
			'label' => 'FIPS Code',
			'name' => 'fips_code',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6601c8e388fd3',
			'label' => 'Fax',
			'name' => 'fax_jurisdiction',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'std_jurisdiction',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'std_jurisdiction',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 1,
) );

	acf_add_local_field_group( array(
	'key' => 'group_67e3592117c26',
	'title' => 'OOJ Details Fields',
	'fields' => array(
		array(
			'key' => 'field_67e35a6b9f618',
			'label' => 'Jurisdiction Selection',
			'name' => 'jurisdiction_selection',
			'aria-label' => '',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'std_jurisdiction',
			),
			'post_status' => array(
				0 => 'publish',
			),
			'taxonomy' => '',
			'return_format' => 'id',
			'multiple' => 0,
			'max' => '',
			'save_custom' => 0,
			'save_post_status' => 'publish',
			'acfe_add_post' => 0,
			'acfe_edit_post' => 0,
			'acfe_bidirectional' => array(
				'acfe_bidirectional_enabled' => '0',
			),
			'allow_null' => 0,
			'allow_in_bindings' => 0,
			'bidirectional' => 0,
			'show_in_graphql' => 1,
			'graphql_description' => '',
			'graphql_field_name' => 'jurisdictionSelection',
			'graphql_connection_type' => 'one_to_many',
			'ui' => 1,
			'bidirectional_target' => array(
			),
			'save_post_type' => '',
			'min' => '',
		),
		array(
			'key' => 'field_67e35b079f619',
			'label' => 'Last Date of Exposure',
			'name' => 'last_date_of_exposure',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'show_in_graphql' => 1,
			'graphql_description' => '',
			'graphql_field_name' => 'lastDateOfExposure',
			'graphql_non_null' => 0,
		),
		array(
			'key' => 'field_67e35b789f61a',
			'label' => 'Dispositions Returned',
			'name' => 'dispositions_returned',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'show_in_graphql' => 1,
			'graphql_description' => '',
			'graphql_field_name' => 'dispositionsReturned',
			'graphql_non_null' => 0,
		),
		array(
			'key' => 'field_67e35b999f61b',
			'label' => 'Accept and Investigate',
			'name' => 'accept_and_investigate',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'show_in_graphql' => 1,
			'graphql_description' => '',
			'graphql_field_name' => 'acceptAndInvestigate',
			'graphql_non_null' => 0,
		),
		array(
			'key' => 'field_67e35bb39f61c',
			'label' => 'Notes',
			'name' => 'notes',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'show_in_graphql' => 1,
			'graphql_description' => '',
			'graphql_field_name' => 'notes',
			'graphql_non_null' => 0,
		),
		array(
			'key' => 'field_67e35bbe9f61d',
			'label' => 'Point of Contact(s)',
			'name' => 'point_of_contacts',
			'aria-label' => '',
			'type' => 'user',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'role' => '',
			'return_format' => 'id',
			'multiple' => 1,
			'min' => '',
			'max' => '',
			'acfe_bidirectional' => array(
				'acfe_bidirectional_enabled' => '0',
			),
			'allow_null' => 0,
			'allow_in_bindings' => 0,
			'bidirectional' => 0,
			'show_in_graphql' => 1,
			'graphql_description' => '',
			'graphql_field_name' => 'pointOfContacts',
			'bidirectional_target' => array(
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'ooj-detail',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 1,
	'acfe_autosync' => '',
	'acfe_form' => 0,
	'acfe_display_title' => '',
	'show_in_graphql' => 1,
	'graphql_field_name' => 'OojDetailsFields',
	'map_graphql_types_from_location_rules' => 0,
	'graphql_types' => '',
	'acfe_meta' => '',
	'acfe_note' => '',
) );

	acf_add_local_field_group( array(
	'key' => 'group_660082a3e05db',
	'title' => 'STD Contact Details',
	'fields' => array(
		array(
			'key' => 'field_660082a497e92',
			'label' => 'HIV Role',
			'name' => 'hiv_role',
			'aria-label' => '',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'hiv-role',
			'add_term' => 0,
			'save_terms' => 0,
			'load_terms' => 0,
			'return_format' => 'object',
			'field_type' => 'multi_select',
			'allow_null' => 0,
			'bidirectional' => 0,
			'multiple' => 0,
			'bidirectional_target' => array(
			),
		),
		array(
			'key' => 'field_6600858197e94',
			'label' => 'STI Role',
			'name' => 'sti_role',
			'aria-label' => '',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'sti-role',
			'add_term' => 0,
			'save_terms' => 0,
			'load_terms' => 0,
			'return_format' => 'object',
			'field_type' => 'multi_select',
			'allow_null' => 0,
			'bidirectional' => 0,
			'multiple' => 0,
			'bidirectional_target' => array(
			),
		),
		array(
			'key' => 'field_6600965b7b847',
			'label' => 'Phone',
			'name' => 'user_phone',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_663934d97c96d',
			'label' => 'Confidential Phone',
			'name' => 'confidential_phone',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6600967a7b848',
			'label' => 'Fax',
			'name' => 'user_fax',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6600968f7b849',
			'label' => 'Notes',
			'name' => 'notes_sti_hiv',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6666208f98b18',
			'label' => 'ACF Jurisdiction',
			'name' => 'user_jurisdiction',
			'aria-label' => '',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'std_jurisdiction',
			),
			'post_status' => array(
				0 => 'publish',
			),
			'taxonomy' => '',
			'return_format' => 'id',
			'multiple' => 0,
			'allow_null' => 0,
			'bidirectional' => 0,
			'ui' => 1,
			'bidirectional_target' => array(
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'user_role',
				'operator' => '==',
				'value' => 'all',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 1,
	'show_in_graphql' => 1,
	'graphql_field_name' => 'stdContactDetails',
	'map_graphql_types_from_location_rules' => 0,
	'graphql_types' => '',
) );
} );

add_action( 'init', function() {
	register_taxonomy( 'acceptable-for-pii', array(
	0 => 'ooj-detail',
), array(
	'labels' => array(
		'name' => 'Acceptable for PIIs ',
		'singular_name' => 'Acceptable for PII ',
		'menu_name' => 'Acceptable for PIIs ',
		'all_items' => 'All Acceptable for PIIs ',
		'edit_item' => 'Edit Acceptable for PII ',
		'view_item' => 'View Acceptable for PII ',
		'update_item' => 'Update Acceptable for PII ',
		'add_new_item' => 'Add New Acceptable for PII ',
		'new_item_name' => 'New Acceptable for PII	Name',
		'search_items' => 'Search Acceptable for PIIs ',
		'popular_items' => 'Popular Acceptable for PIIs ',
		'separate_items_with_commas' => 'Separate acceptable for piis	with commas',
		'add_or_remove_items' => 'Add or remove acceptable for piis ',
		'choose_from_most_used' => 'Choose from the most used acceptable for piis ',
		'not_found' => 'No acceptable for piis	found',
		'no_terms' => 'No acceptable for piis ',
		'items_list_navigation' => 'Acceptable for PIIs	list navigation',
		'items_list' => 'Acceptable for PIIs	list',
		'back_to_items' => '← Go to acceptable for piis ',
		'item_link' => 'Acceptable for PII	Link',
		'item_link_description' => 'A link to a acceptable for pii ',
	),
	'public' => true,
	'show_in_menu' => true,
	'show_in_rest' => true,
	'show_in_graphql' => true,
	'graphql_single_name' => 'acceptableForPii',
	'graphql_plural_name' => 'acceptableForPiis',
) );

	register_taxonomy( 'hiv-role', array(
	0 => 'ooj-detail',
), array(
	'labels' => array(
		'name' => 'HIV Roles',
		'singular_name' => 'HIV Role',
		'menu_name' => 'HIV Roles',
		'all_items' => 'All HIV Roles',
		'edit_item' => 'Edit HIV Role',
		'view_item' => 'View HIV Role',
		'update_item' => 'Update HIV Role',
		'add_new_item' => 'Add New HIV Role',
		'new_item_name' => 'New HIV Role Name',
		'search_items' => 'Search HIV Roles',
		'popular_items' => 'Popular HIV Roles',
		'separate_items_with_commas' => 'Separate hiv roles with commas',
		'add_or_remove_items' => 'Add or remove hiv roles',
		'choose_from_most_used' => 'Choose from the most used hiv roles',
		'not_found' => 'No hiv roles found',
		'no_terms' => 'No hiv roles',
		'items_list_navigation' => 'HIV Roles list navigation',
		'items_list' => 'HIV Roles list',
		'back_to_items' => '← Go to hiv roles',
		'item_link' => 'HIV Role Link',
		'item_link_description' => 'A link to a hiv role',
	),
	'public' => true,
	'show_in_menu' => true,
	'show_in_rest' => true,
	'show_in_quick_edit' => true,
	'meta_box_cb' => false,
	'show_in_graphql' => true,
	'graphql_single_name' => 'hIVRole',
	'graphql_plural_name' => 'hIVRoles',
) );

	register_taxonomy( 'iccr_method-of-transmitting', array(
	0 => 'ooj-detail',
), array(
	'labels' => array(
		'name' => 'Methods of Transmitting ',
		'singular_name' => 'Method of Transmitting ',
		'menu_name' => 'Methods of Transmitting ',
		'all_items' => 'All Methods of Transmitting ',
		'edit_item' => 'Edit Method of Transmitting ',
		'view_item' => 'View Method of Transmitting ',
		'update_item' => 'Update Method of Transmitting ',
		'add_new_item' => 'Add New Method of Transmitting ',
		'new_item_name' => 'New Method of Transmitting	Name',
		'search_items' => 'Search Methods of Transmitting ',
		'popular_items' => 'Popular Methods of Transmitting ',
		'separate_items_with_commas' => 'Separate methods of transmitting	with commas',
		'add_or_remove_items' => 'Add or remove methods of transmitting ',
		'choose_from_most_used' => 'Choose from the most used methods of transmitting ',
		'not_found' => 'No methods of transmitting	found',
		'no_terms' => 'No methods of transmitting ',
		'items_list_navigation' => 'Methods of Transmitting	list navigation',
		'items_list' => 'Methods of Transmitting	list',
		'back_to_items' => '← Go to methods of transmitting ',
		'item_link' => 'Method of Transmitting	Link',
		'item_link_description' => 'A link to a method of transmitting ',
	),
	'public' => true,
	'show_in_menu' => true,
	'show_in_rest' => true,
	'show_in_graphql' => true,
	'graphql_single_name' => 'methodOfTransmitting',
	'graphql_plural_name' => 'methodsOfTransmitting',
) );

	register_taxonomy( 'acf-ooj-activity', array(
	0 => 'ooj-detail',
), array(
	'labels' => array(
		'name' => 'OOJ Activities',
		'singular_name' => 'OOJ Activity',
		'menu_name' => 'OOJ Activities',
		'all_items' => 'All OOJ Activities',
		'edit_item' => 'Edit OOJ Activity',
		'view_item' => 'View OOJ Activity',
		'update_item' => 'Update OOJ Activity',
		'add_new_item' => 'Add New OOJ Activity',
		'new_item_name' => 'New OOJ Activity Name',
		'search_items' => 'Search OOJ Activities',
		'popular_items' => 'Popular OOJ Activities',
		'separate_items_with_commas' => 'Separate ooj activities with commas',
		'add_or_remove_items' => 'Add or remove ooj activities',
		'choose_from_most_used' => 'Choose from the most used ooj activities',
		'not_found' => 'No ooj activities found',
		'no_terms' => 'No ooj activities',
		'items_list_navigation' => 'OOJ Activities list navigation',
		'items_list' => 'OOJ Activities list',
		'back_to_items' => '← Go to ooj activities',
		'item_link' => 'OOJ Activity Link',
		'item_link_description' => 'A link to a ooj activity',
	),
	'public' => true,
	'show_in_menu' => true,
	'show_in_rest' => true,
	'show_tagcloud' => false,
	'show_in_quick_edit' => false,
	'show_in_graphql' => true,
	'graphql_single_name' => 'oOJActivity',
	'graphql_plural_name' => 'oOJActivities',
) );

	register_taxonomy( 'acf-ooj-infection', array(
	0 => 'ooj-detail',
), array(
	'labels' => array(
		'name' => 'OOJ Infections',
		'singular_name' => 'OOJ Infection',
		'menu_name' => 'OOJ Infections',
		'all_items' => 'All OOJ Infections',
		'edit_item' => 'Edit OOJ Infection',
		'view_item' => 'View OOJ Infection',
		'update_item' => 'Update OOJ Infection',
		'add_new_item' => 'Add New OOJ Infection',
		'new_item_name' => 'New OOJ Infection Name',
		'search_items' => 'Search OOJ Infections',
		'popular_items' => 'Popular OOJ Infections',
		'separate_items_with_commas' => 'Separate ooj infections with commas',
		'add_or_remove_items' => 'Add or remove ooj infections',
		'choose_from_most_used' => 'Choose from the most used ooj infections',
		'not_found' => 'No ooj infections found',
		'no_terms' => 'No ooj infections',
		'items_list_navigation' => 'OOJ Infections list navigation',
		'items_list' => 'OOJ Infections list',
		'back_to_items' => '← Go to ooj infections',
		'item_link' => 'OOJ Infection Link',
		'item_link_description' => 'A link to a ooj infection',
	),
	'public' => true,
	'show_in_menu' => true,
	'show_in_rest' => true,
	'show_in_graphql' => true,
	'graphql_single_name' => 'oOJInfection',
	'graphql_plural_name' => 'oOJInfections',
) );

	register_taxonomy( 'sti-role', array(
	0 => 'ooj-detail',
), array(
	'labels' => array(
		'name' => 'STI Roles',
		'singular_name' => 'STI Role',
		'menu_name' => 'STI Roles',
		'all_items' => 'All STI Roles',
		'edit_item' => 'Edit STI Role',
		'view_item' => 'View STI Role',
		'update_item' => 'Update STI Role',
		'add_new_item' => 'Add New STI Role',
		'new_item_name' => 'New STI Role Name',
		'search_items' => 'Search STI Roles',
		'popular_items' => 'Popular STI Roles',
		'separate_items_with_commas' => 'Separate sti roles with commas',
		'add_or_remove_items' => 'Add or remove sti roles',
		'choose_from_most_used' => 'Choose from the most used sti roles',
		'not_found' => 'No sti roles found',
		'no_terms' => 'No sti roles',
		'items_list_navigation' => 'STI Roles list navigation',
		'items_list' => 'STI Roles list',
		'back_to_items' => '← Go to sti roles',
		'item_link' => 'STI Role Link',
		'item_link_description' => 'A link to a sti role',
	),
	'public' => true,
	'show_in_menu' => true,
	'show_in_rest' => true,
	'show_in_quick_edit' => true,
	'meta_box_cb' => false,
	'show_in_graphql' => true,
	'graphql_single_name' => 'sTIRole',
	'graphql_plural_name' => 'sTIRoles',
) );
} );

add_action( 'init', function() {
	register_post_type( 'std_jurisdiction', array(
	'labels' => array(
		'name' => 'Jurisdictions',
		'singular_name' => 'Jurisdiction',
		'menu_name' => 'Jurisdictions',
		'all_items' => 'All Jurisdictions',
		'edit_item' => 'Edit Jurisdiction',
		'view_item' => 'View Jurisdiction',
		'view_items' => 'View Jurisdictions',
		'add_new_item' => 'Add New Jurisdiction',
		'add_new' => 'Add New Jurisdiction',
		'new_item' => 'New Jurisdiction',
		'parent_item_colon' => 'Parent Jurisdiction:',
		'search_items' => 'Search Jurisdictions',
		'not_found' => 'No jurisdictions found',
		'not_found_in_trash' => 'No jurisdictions found in Trash',
		'archives' => 'Jurisdiction Archives',
		'attributes' => 'Jurisdiction Attributes',
		'insert_into_item' => 'Insert into jurisdiction',
		'uploaded_to_this_item' => 'Uploaded to this jurisdiction',
		'filter_items_list' => 'Filter jurisdictions list',
		'filter_by_date' => 'Filter jurisdictions by date',
		'items_list_navigation' => 'Jurisdictions list navigation',
		'items_list' => 'Jurisdictions list',
		'item_published' => 'Jurisdiction published.',
		'item_published_privately' => 'Jurisdiction published privately.',
		'item_reverted_to_draft' => 'Jurisdiction reverted to draft.',
		'item_scheduled' => 'Jurisdiction scheduled.',
		'item_updated' => 'Jurisdiction updated.',
		'item_link' => 'Jurisdiction Link',
		'item_link_description' => 'A link to a jurisdiction.',
	),
	'public' => true,
	'show_in_rest' => true,
	'menu_icon' => 'dashicons-admin-post',
	'supports' => array(
		0 => 'title',
		1 => 'revisions',
	),
	'delete_with_user' => false,
	'show_in_graphql' => true,
	'graphql_single_name' => 'jurisdiction',
	'graphql_plural_name' => 'jurisdictions',
) );

	register_post_type( 'ooj-detail', array(
	'labels' => array(
		'name' => 'OOJ Details',
		'singular_name' => 'OOJ Detail',
		'menu_name' => 'OOJ Details',
		'all_items' => 'All OOJ Details',
		'edit_item' => 'Edit OOJ Detail',
		'view_item' => 'View OOJ Detail',
		'view_items' => 'View OOJ Details',
		'add_new_item' => 'Add New OOJ Detail',
		'add_new' => 'Add New OOJ Detail',
		'new_item' => 'New OOJ Detail',
		'parent_item_colon' => 'Parent OOJ Detail:',
		'search_items' => 'Search OOJ Details',
		'not_found' => 'No ooj details found',
		'not_found_in_trash' => 'No ooj details found in Trash',
		'archives' => 'OOJ Detail Archives',
		'attributes' => 'OOJ Detail Attributes',
		'insert_into_item' => 'Insert into ooj detail',
		'uploaded_to_this_item' => 'Uploaded to this ooj detail',
		'filter_items_list' => 'Filter ooj details list',
		'filter_by_date' => 'Filter ooj details by date',
		'items_list_navigation' => 'OOJ Details list navigation',
		'items_list' => 'OOJ Details list',
		'item_published' => 'OOJ Detail published.',
		'item_published_privately' => 'OOJ Detail published privately.',
		'item_reverted_to_draft' => 'OOJ Detail reverted to draft.',
		'item_scheduled' => 'OOJ Detail scheduled.',
		'item_updated' => 'OOJ Detail updated.',
		'item_link' => 'OOJ Detail Link',
		'item_link_description' => 'A link to a ooj detail.',
	),
	'public' => true,
	'show_in_rest' => true,
	'menu_icon' => 'dashicons-admin-post',
	'supports' => array(
		0 => 'title',
		1 => 'revisions',
	),
	'taxonomies' => array(
		0 => 'hiv-role',
		1 => 'acf-ooj-infection',
		2 => 'acf-ooj-activity',
		3 => 'sti-role',
		4 => 'iccr_method-of-transmitting',
		5 => 'acceptable-for-pii',
	),
	'delete_with_user' => false,
	'show_in_graphql' => true,
	'graphql_single_name' => 'oOJDetail',
	'graphql_plural_name' => 'oOJDetails',
) );
} );

